# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssherpa < Formula
  desc "SSH connection manager with project context and 1Password integration"
  homepage "https://github.com/florianriquelme/ssherpa"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/florianriquelme/ssherpa/releases/download/v0.1.0/ssherpa_0.1.0_darwin_amd64.tar.gz"
      sha256 "13f641ef7105077242c6bbb80d22a58b23e4c38f8d67d2485c8403f3de25efa3"

      def install
        bin.install "ssherpa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/florianriquelme/ssherpa/releases/download/v0.1.0/ssherpa_0.1.0_darwin_arm64.tar.gz"
      sha256 "f102dfdb402db3ec2022b26a2a2916f7949abd29ccf742ae5f783ca0955e65da"

      def install
        bin.install "ssherpa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/florianriquelme/ssherpa/releases/download/v0.1.0/ssherpa_0.1.0_linux_amd64.tar.gz"
      sha256 "2de259b383a6d88bbf0cbdb7d112da0e5cff5e1ce0ad470e9ae3134075643e4e"
      def install
        bin.install "ssherpa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/florianriquelme/ssherpa/releases/download/v0.1.0/ssherpa_0.1.0_linux_arm64.tar.gz"
      sha256 "a187c44888a53919186b1ac675c42ac9bc567ddd2c43b968355382411ea4c272"
      def install
        bin.install "ssherpa"
      end
    end
  end

  test do
    system "#{bin}/ssherpa", "version"
  end
end
